language: objective-c

before_install: 
- brew update
- brew upgrade xctool

script: 
- xctool -project BButtonDemo.xcodeproj -scheme BButtonDemo -sdk iphonesimulator7.0 ONLY_ACTIVE_ARCH=NO clean build test 
